apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: abrahamosaz/mail-service:1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MAIL_DOMAIN
            value: "localhost"
          - name: MAIL_HOST
            value: "mailhog"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_FROM_NAME
            value: "Abraham"
          - name: MAIL_FROM_ADDRESS
            value: "abraham@gmail.com"
        ports:
          - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      name: main-port
      port: 5005
      targetPort: 5005
