version: "3"

services:
  auth-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ab
      POSTGRES_PASSWORD: abraham
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/auth-postgres:/var/lib/postgresql/data

